### ISSUE TITLE
pymobiledevice3.exceptions.MissingValueError: MissingValue

### ISSUE THREAD

**Issue by Mickept** [prosch88/UFADE#1]
Traceback (most recent call last):

  File "/home/micke/Tools/UFADE/./ufade.py", line 766, in <module>───────────────────────────────────────────────────────────────────────────────────────────────────────────────

    wrapper(select_menu)

  File "/usr/lib/python3.11/curses/__init__.py", line 94, in wrapper

    return func(stdscr, *args, **kwds)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/micke/Tools/UFADE/./ufade.py", line 82, in select_menu

    save_info_menu()

  File "/home/micke/Tools/UFADE/./ufade.py", line 177, in save_info_menu

    wrapper(select_menu)

  File "/usr/lib/python3.11/curses/__init__.py", line 94, in wrapper

    return func(stdscr, *args, **kwds)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/micke/Tools/UFADE/./ufade.py", line 92, in select_menu

    developer_options()

  File "/home/micke/Tools/UFADE/./ufade.py", line 679, in developer_options

    wrapper(select_menu)

  File "/usr/lib/python3.11/curses/__init__.py", line 94, in wrapper

    return func(stdscr, *args, **kwds)                       ┌────────────────────────────────────────────────────┐

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^                       │ Performing Extraction of Shared App-Files          │  

  File "/home/micke/Tools/UFADE/./ufade.py", line 88, in select_menu                                              │  

    perf_logical_plus("UFED")                                │                                                    │  

  File "/home/micke/Tools/UFADE/./ufade.py", line 496, in perf_logical_plus────────────────────────────────────┐  │  

    de_va_di.update([(key,(lockdown.get_value("",key)))])    │  │                     100%                     │  │  

                           ^^^^^^^^^^^^^^^^^^^^^^^^^^        │  └──────────────────────────────────────────────┘  │  

  File "/home/micke/.local/lib/python3.11/site-packages/pymobiledevice3/lockdown.py", line 54, in _inner_reconnect_on_remote_close

    return f(*args, **kwargs)                                  

           ^^^^^^^^^^^^^^^^^^

  File "/home/micke/.local/lib/python3.11/site-packages/pymobiledevice3/lockdown.py", line 376, in get_value

    res = self._request('GetValue', options)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/micke/.local/lib/python3.11/site-packages/pymobiledevice3/lockdown.py", line 498, in _request

    raise exception_errors.get(error, LockdownError)(error)

pymobiledevice3.exceptions.MissingValueError: MissingValue

**Comment by Mickept** [comment]
i'm using arch linux by the way

**Comment by prosch88** [comment]
I'm using Arch too.
Which device are you trying to acquire?

**Comment by Mickept** [comment]
SE 2022

**Comment by prosch88** [comment]
OK, should be fixed.
Problem was the generation of info-files for the PA structure. Pull and try again.

**Comment by Mickept** [comment]
Done!! i Will open it in PA... Thenks
